### ISSUE TITLE
Creation or Edit of File multiple directories deep fails

### ISSUE THREAD

**Issue by cjpais** [kkuo42/CSE223B-FinalProject#11]
Title.

To reproduce use the interactive test.

Stay in the data directory and run mkdir -p to0/test/test/test/test
Then use vim and open to0/test/test/test/test/test.txt

This will produce a failure upon ReplicaWrite. There is some recursive directory creation but it doesn't seem to be helping

**Comment by sqamara** [comment]
resolved at da8d46b80d121e3c04c23ce3b80e800baf936363
